#general {
#    no_fade_in = false
#    disable_loading_bar = true
#}

background {
    monitor = eDP-1
    path = /home/user/Downloads/99px_ru_wallpaper_331665_ninomae_inanis_s_krasnim_zontom_stoit_u_vrat.jpg
    blur_passes = 2
    blur_size = 2
    contrast = 1
    bringhtess = 0.8
    vibrancy = 0.16
    vibrancy_darkness = 0.1
}

label {
    monitor = eDP-1
    text = $TIME
    color = rgba(200, 200, 200, 0.9)5
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = ЗИГ Х**ль друже
    color = rgba(200, 200, 200, 0.95)
    font_size = 22
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = $LAYOUT
    color = rgba(200, 200, 200, 0.9)
    font_size = 15
    font_family = JetBrains Mono
    position = 30, -30
    halign = left
    valign = top
}

image {
    monitor =eDP-1
    path = /home/user/Downloads/image/gay.png
    size = 150
    valign = center
    halign = center
    border_size = 1
    border_color = rgba(200, 200, 200, 0.9)
    rouding = 0
    position = 0, -30
}

input-field {
    monitor =eDP-1
    size = 250, 60
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    placeholder_text = ПИШИ, ЧЁ СМОТРИШЬ
    fade_on_empty = false
    fade_timeout = 100000
    fail_text = ПЕРЕДЕЛЫВАЙ KURWA
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgba(220, 215, 186, 0.8)
    font_family = JetBrains Mono
    check_color = rgb(204, 136, 34)
    position = 0, -200
    halign = center
    valign = center
}

